
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x9a\xb8\x82\x18\x85\xe4\xb9\xce\xe3\xc6F\x0b\xd1\x94\xd0\x0c'
    
_lr_action_items = {'VAR':([0,1,2,3,4,5,6,7,8,9,],[1,-7,-6,1,1,-1,-5,-2,-4,-3,]),'NUMBER':([0,1,2,3,4,5,6,7,8,9,],[2,-7,-6,2,2,-1,-5,-2,-4,-3,]),'$end':([1,2,3,5,6,7,8,9,],[-7,-6,0,-1,-5,-2,-4,-3,]),'DIVIDE':([1,2,4,5,6,7,8,9,],[-7,-6,6,-1,-5,-2,-4,-3,]),'PLUS':([1,2,4,5,6,7,8,9,],[-7,-6,7,-1,-5,-2,-4,-3,]),'EQUAL':([1,2,4,5,6,7,8,9,],[-7,-6,5,-1,-5,-2,-4,-3,]),'TIMES':([1,2,4,5,6,7,8,9,],[-7,-6,8,-1,-5,-2,-4,-3,]),'MINUS':([1,2,4,5,6,7,8,9,],[-7,-6,9,-1,-5,-2,-4,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,4,],[3,4,4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr expr EQUAL','expr',3,'p_expr_equal','ep5.py',34),
  ('expr -> expr expr PLUS','expr',3,'p_expr_plus','ep5.py',47),
  ('expr -> expr expr MINUS','expr',3,'p_expr_minus','ep5.py',52),
  ('expr -> expr expr TIMES','expr',3,'p_expr_times','ep5.py',57),
  ('expr -> expr expr DIVIDE','expr',3,'p_expr_divide','ep5.py',62),
  ('expr -> NUMBER','expr',1,'p_expr_number','ep5.py',71),
  ('expr -> VAR','expr',1,'p_expr_var','ep5.py',78),
]
